### GET todas as consultas
GET http://localhost:8080/api/consultas
Accept: application/json

### GET consulta por ID
GET http://localhost:8080/api/consultas/2
Accept: application/json

### POST criar nova consulta
POST http://localhost:8080/api/consultas
Content-Type: application/json
Accept: application/json

{
  "pacienteId": 1,
  "profissionalId": 1,
  "especialidadeId": 1,
  "data": "2025-01-01",
  "horario": "10:30",
  "observacoes": "Paciente com dores na coluna.",
  "status": "Agendada"
}




### PUT atualizar consulta por ID
PUT http://localhost:8080/api/consultas/1
Content-Type: application/json
Accept: application/json

{
  "pacienteId": 1,
  "profissionalId": 1,
  "especialidadeId": 1,
  "data": "2025-01-01",
  "horario": "10:30",
  "observacoes": "Paciente com dores na coluna.",
  "status": "Agendada"
}


### DELETE consulta por ID
DELETE http://localhost:8080/api/consultas/{id}
Accept: application/json
